[package]
name = "peach-oled"
version = "0.1.0"
authors = ["Andrew Reid <gnomad@cryptolab.net>"]

[dependencies]
linux-embedded-hal = "0.2.2"
embedded-graphics = "0.4.7"
machine-ip = "0.2.1"
tinybmp = "0.1.0"
ssd1306 = "0.2.4"
